### ISSUE TITLE
I can't relate to steam

### ISSUE THREAD

**Issue by 1456158721** [gogcom/galaxy-integrations-python-api#100]
I'm from China, and I've opened VPN. I can test that I can access Google and steam community, but I still can't open the page associated with steam, like this:
![1](https://user-images.githubusercontent.com/35886522/70890161-51ff9200-201f-11ea-8688-01c07ecf9e23.png)

**Comment by fatinghenji** [comment]
老哥你可以用steamcommunity解决这个问题。需要勾选使用服务器反代，如果出现封面加载问题可以用加速器加速GOG。

**Comment by 1456158721** [comment]
> 老哥你可以用steamcommunity解决这个问题。需要勾选使用服务器反代，如果出现封面加载问题可以用加速器加速GOG。

我挂VPN都不行，挂个反代就行了？什么原理。。。

**Comment by fatinghenji** [comment]
具体不知道……我也是在百度上面找到的方案……这个应该不是GOG能解决的，我觉着是steam的问题。毕竟国情导致steam社区打不开。GOG是通过访问你的社区页面来导入你的游戏库的

**Comment by Sultzor** [comment]
This issue should be reported here:
https://github.com/FriendsOfGalaxy/galaxy-integration-steam

**Comment by mbanczerowski** [comment]
Closing as not related to the API
