### ISSUE TITLE
Add lutris platform id

### ISSUE THREAD

**Issue by bjoern-tantau** [gogcom/galaxy-integrations-python-api#101]
We could use a platform ID to integrate Lutris, as you can manage many different games from many different sources with it and some people might have set that up already.

Beyond that a deeper integration between Galaxy 2.0 and Lutris would probably be beneficial to both as they have similar goals in combining games from several sources into one place but could also give GOG a better Linux support going forward. But I guess this is out of scope for this ticket, so just a platform ID would be a good start.

**Comment by mbanczerowski** [comment]
I'm not sure if having other platforms integrated by any proxy would be valid for how Galaxy works and presents data:
- you will lost real games origin (they had to be displayed as "lutris" games)
- probably most valuable functionalities like install/play are unavailable

Though I understand that some people might have set that up already and it would be easy to add. If you still think it may be useful you can request it in this thread: #160 .
