### ISSUE TITLE
REQUEST:  Star Citizen Launcher Integration Please?

### ISSUE THREAD

**Issue by caspersonit** [gogcom/galaxy-integrations-python-api#104]
Hi guys,
Wondering if someone may be able to magic up an integration to the RSI Star Citizen Launcher?
To download the launcher you need to own the game however, although I am sure you could get it from another member - like myself - if you don't have the game.
The official site of the game is www.robertsspaceindustries.com
It will be the launcher for both the Single player Squadron 42 game and the MMO part called Star Citizen.
Approx 1.5 to 2 million players at this stage of beta so it is certainly big enough to warrant a look!?
Thanks Guys!

**Comment by caspersonit** [comment]
Sorry, saw this is the wrong place to ask - CLOSED ISSUE

**Comment by Mixaill** [comment]
https://github.com/Mixaill/awesome-gog-galaxy/issues/63
