### ISSUE TITLE
Removing unwanted Galaxy integrations

### ISSUE THREAD

**Issue by ElAlderson** [gogcom/galaxy-integrations-python-api#107]
There should be a way to remove integrations from the galaxy client. Personally, I have a problem with the Rockstar Games integration which was formerly called "Riot" for some reason. I had integrated "Riot" then which was still under development and after the "official" launch, I integrated Rockstar Games. But Riot still shows up. My Rockstar games also show up under Riot. Even tried deleting the Riot plugin folders but in vain.
![Capture](https://user-images.githubusercontent.com/35873183/71655920-2f7bb180-2d5f-11ea-84c2-2ca373afc7c4.PNG)

**Comment by rbierbasz-gog** [comment]
The problem you reported is related with Galaxy Client, not integration API (you should report he bug using cogwheel -> Report Issue), but I'll try to help.
You can disconnect an external account only with connected plugin - so if you have connected Riot account you should reconnect the Riot plugin (if it's not already connected) and press disconnect.

**Comment by ElAlderson** [comment]
Thank you, the issue has been resolved by following your steps. But within the integration API, it would be cool if a feature to remove the integrations can be implemented.
