### ISSUE TITLE
Integrations, game finder and philosophy...

### ISSUE THREAD

**Issue by vmwinckler** [gogcom/galaxy-integrations-python-api#109]
today on client: (2.0.12 Beta - December 12, 2019)

1º: Integrations 
- "exists" but don't find(and important for PC): gog, discord, riot(!!!), gmg, amazon(now exists "amazon games too"), fanatical, eso(but bethesda works for same),weplay,blade(b&s), pathofexile(but steam works for same), twitch(great possibilites*)
- auto disconect: epic and rockstar
- sugests add: Glyph(Arche Age and others), Game Center(Lost Ark RU), Valofe (Icarus "not steam" and others), mixer(if has twitch need mixer too if pretend use stream conections*), 

2º: game finder
- I used "find games" on my directory "games" and client dont find noting more... but after i add maually: Black Desert Online(from Red Fox), Honkay Impact 3rd a Magic: The Gathering Arena... all in this same directory

3º: Other suggestion: add mark "cross-plataform" filter. Example: Fortinite, Dauntless, Dota Underlords and Others

*focus: i see other suggestions over integrations with nexus(addons, templates), twitch has game database but has born "amazon games",  need review this type integration an principaly: Need delcare for all: GoG Galaxy is ONLY for games only or for add ALL? (mods, addons, skins, streams, and all).

PS.: Need review Friend List "intelligence" for auto organization/unification 

tanks for patience ;)

**Comment by mbanczerowski** [comment]
@vmwinckler thanks for your feedback.

I have to close this as too general and mostly unrelated to this project, but could you please report your issues separately [here](https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose)?

1º , 3º is for platform ids and community integrations (see link above)

2º Quick answer: "find games" works for GOG games releases only. Adding manually works for any executable.
