### ISSUE TITLE
Steam Family Sharing & Amazon Prime Games

### ISSUE THREAD

**Issue by Blootrix** [gogcom/galaxy-integrations-python-api#110]
Not being able to see the games I have access to through Steam Family Sharing is the main reason I'm not using GOG Galaxy 2.0. Is there any chance this will be added at some point?

Support for Games With Prime would be great too, I have 50+ games through Amazon.

**Comment by RelativeProgramming** [comment]
The Prime games are shown if you use the Twitch plugin

**Comment by Blootrix** [comment]
> The Prime games are shown if you use the Twitch plugin

Does the Twitch Plugin count as official support or is it third party?

**Comment by RelativeProgramming** [comment]
I think it is 3rd party

**Comment by RelativeProgramming** [comment]
You can find it here (along with other 3rd party plugins): https://github.com/Mixaill/awesome-gog-galaxy

**Comment by Croydon** [comment]
What is the reason that some integrations can't be found within Galaxy?

**Comment by Blootrix** [comment]
> You can find it here (along with other 3rd party plugins): https://github.com/Mixaill/awesome-gog-galaxy

Thank you for linking that, I'll give it a shot and hopefully it works.

**Comment by mbanczerowski** [comment]
Steam Family Sharing is done in community plugin: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/12

both `amazon` and `twitch` are in platform game list. Closing as not problem with Amazon Prime support is not related to this repository anymore.
