### ISSUE TITLE
Hours tracked wrong..

### ISSUE THREAD

**Issue by Edstub207** [gogcom/galaxy-integrations-python-api#111]
hey!

Looks like the hours tracked in game are wrong. I've played ~200 hours on Destiny 2 since the move to Steam. 

However, in the months since then I've only played ~100 hours across ALL games supposedly.

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.
