### ISSUE TITLE
GTA Online (Rockstar integration) does not track hours

### ISSUE THREAD

**Issue by naobug** [gogcom/galaxy-integrations-python-api#113]
HI,
although I have successfully connected GOG with the Rockstar plugin and also lists GTA5/GTAOline it does not track my game hours although I started it through GOG (which starts the Rockstar launcher, which starts GTA5, where I then select "play online").

Before I used the Rockstar plugin and just added the GTA exe I could track the hours. But with the plugin it doesn't work.

**Comment by mbanczerowski** [comment]
Hi, Rockstar plugin is third-party open source project outside of GOG Team scope. 
Please report the issue on integration page: https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar
