### ISSUE TITLE
Adding Twitch

### ISSUE THREAD

**Issue by B1GP7** [gogcom/galaxy-integrations-python-api#114]
Adding support for twitch connection and see twitch games

**Comment by ThunderOne1** [comment]
+1

**Comment by goldenmobster** [comment]
+1

**Comment by GreyAria** [comment]
+1

**Comment by n-t0r** [comment]
+1 here

**Comment by Croydon** [comment]
Please use GitHub 👍 reactions on the issue, instead of creating "+1" comments. Thanks! 😄

**Comment by Mixaill** [comment]
https://github.com/nyash-qq/galaxy-plugin-twitch/releases

**Comment by Hatsum** [comment]
> 
> 
> https://github.com/nyash-qq/galaxy-plugin-twitch/releases

Unfortunately, this plugin don't work anymore because Twitch games are now moved to the new Amazon Games launcher :(

**Comment by Rall3n** [comment]
> > https://github.com/nyash-qq/galaxy-plugin-twitch/releases
> 
> Unfortunately, this plugin don't work anymore because Twitch games are now moved to the new Amazon Games launcher :(

Can`t confirm for now. If you claim a game on the Twitch Prime site, you are recommended to download the Amazon Games app, but they still mention that the games are also available in the Twitch App.

Also there is no news or other indication that the games will be removed from the Twitch App.

**Comment by Q-efx** [comment]
I would guess that New world will be "Amazon" exclusive and won't be available on Twitch app...

**Comment by Primajin** [comment]
![amazon-twitch](https://user-images.githubusercontent.com/1742115/81473668-50b64800-9200-11ea-8f15-0d5762c63a13.png)
![amazon-twitch-2](https://user-images.githubusercontent.com/1742115/81473670-51e77500-9200-11ea-92ab-6f1ba0959d54.png)

Amazon integration works for me with all my Twitch Games

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.
