### ISSUE TITLE
Question: Setting multiple games as Running at the same time

### ISSUE THREAD

**Issue by UmbyUmbreon** [gogcom/galaxy-integrations-python-api#115]
I'm currently working on some fixes and enhancements to an integration, and part of these enhancements is adding another game to the list if a certain launcher is installed by the user.

At the moment, running one game will set them both to a Running state to prevent multiple launcher windows from appearing. Is this an acceptable way of handling this scenario, and if not, what are the best practices for setting game states? Additionally, would doing things this way have a detrimental effect on time tracking if this was implemented into Galaxy itself (eg: playtime doubling because two games are "running" at once)?

**Comment by mbanczerowski** [comment]
Hi, could you please describe your issue more clearly?

> part of these enhancements is adding another game to the list 
I see you have forked FFXIV integration. Isn't it one-game plugin? If there are more games added to a launcher, then yes - they should be reported separately.

> At the moment, running one game will set them both to a Running state
It shouldn't happen. Probably the plugin is tracking launcher process. In your enhancement it should track each game separately. 

Note that searching for processes through the whole process list is not optimal and affects 
users computer performance. Make sure your processes tree search is rare / called on demand.

>  Additionally, would doing things this way have a detrimental effect on time tracking if this was implemented into Galaxy itself (eg: playtime doubling because two games are "running" at once)?

Yes it has side effect. Each game running status change update "last played" time. Time tracking this way is implemented only for manually added games (not for games added by integrations)

**Comment by mbanczerowski** [comment]
@UmbyUmbreon did my previous comment answer your question?

**Comment by UmbyUmbreon** [comment]
Yep, that works fine by me. Thanks!
