### ISSUE TITLE
Question: Refresh game time upon exiting game

### ISSUE THREAD

**Issue by Brummos** [gogcom/galaxy-integrations-python-api#117]
I'm working on a plugin. But i can't seem to get the refresh for game times working.

What exactly do i need to do to make the game time refresh when the game exits? Which functions do i need to call or implement?

At the moment it works only when the plugin restarts

Thanks :)

**Comment by mbanczerowski** [comment]
Philosophically Galaxy ask can trigger any method when it needs to.

Currently there are a few events when Galaxy calls getting game times (and achievements):
- on start (all games reported from `get_owned_games`)
- periodically after some time every 6 hours (all games reported from `get_owned_games`)
- when user has requested full plugins refresh for all plugins via (cogwheel manu -> Sync integrations). However this is possible once per 10min or 15min I don't remember exactly.
- when a user has stopped playing a game launched via Galaxy (`const.LocalGameState` has changed from "Running" to "Installed" in `update_game` notification) (only for the just played game)

From the API side, Galaxy triggers `start_game_times_import` API method with a list of  `games_id` . This is internally processed to call `prepare_game_times_context` and then `get_game_time(game_id, context)` for each game id from `games_id` list with previously prepared context as the second argument. This internally sends a bunch of notifications back to Galaxy. At the end `game_times_import_complete` is called. All those 3 methods are intended to be overridden by a plugin creator (`get_game_time` is a minimum). This is a common pattern for many things in the API.

I you have any other questions or need more clarification, don't hesitate to ask!

**Comment by Brummos** [comment]
Perfect information, thank you very much. I think this will help me a lot. Now I also know that I am doing some other stuff wrong. Might have some questions later, but for now this was all i needed :)
