### ISSUE TITLE
GOG Galaxy 2 is registered with one Steam account but loads up the game from a different Steam account.

### ISSUE THREAD

**Issue by gaveitatry02** [gogcom/galaxy-integrations-python-api#118]
I have two Steam accounts.

One account starts with a 'C'.  It's my main account.

My other account starts with a 'P'.

Both accounts have a copy of the game "PAYDAY 2".

Also, I have Family Sharing enabled, but that probably doesn't matter.

Earlier today, I played "PAYDAY 2" on my 'P' account.  I thought I was playing it from Family Sharing, but most likely I was just playing the copy that my 'P' account owned.  I obtained three achievements and then logged off.

I don't want to play "PAYDAY 2" on my 'C' account because the game has nearly 1,000 achievements and I might end up not liking the game.

Instead of logging out of 'C' on Steam and then logging in on 'P', playing for 30 minutes, and then logging back in on 'C' using Steam Guard codes and crap, I thought it would make my life a lot easier to use GOG Galaxy for my 'P' account.  So I installed GOG Galaxy 2 and I linked my 'P' Steam account.  After it was linked, it showed the five games that my 'P' account owns, so it didn't count the games from Family Sharing.  That's fine.  I don't care.  It also showed the three achievements that I already got on my 'P' account.  Cool.  But then when I launched the game, it had launched my 'C' account's "PAYDAY 2".  In other words, it's the same exact thing as opening up Steam on my 'C' account and clicking Play, even though I specifically used my 'P' account to sign in on GOG Galaxy 2.

I can't use your program because of this.  Hopefully you understand.  Thanks.

**Comment by mbanczerowski** [comment]
Hey, please open this issue in Steam integration repository: https://github.com/FriendsOfGalaxy/galaxy-integration-steam
I'm closing it as not related to this repository.
