### ISSUE TITLE
Adding Riot Games/ League of Legends

### ISSUE THREAD

**Issue by leti96** [gogcom/galaxy-integrations-python-api#119]
Any option for Riot client?

**Comment by jashazzard** [comment]
I would like an option for this as well!!

**Comment by mbanczerowski** [comment]
[riot](https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py#L25) platform id is already added.

Integration request on community repo: https://github.com/Mixaill/awesome-gog-galaxy/issues/48
