### ISSUE TITLE
Mobile device platforms:

### ISSUE THREAD

**Issue by gjgfuj** [gogcom/galaxy-integrations-python-api#122]
I would like at least these platforms added to the platform list for the sake of integration with mobile app stores:

- Google Play Store
- Apple App Store
- Amazon App Store

Any others I missed?

(I'm planning on making a google play store integration so will temporarily use Stadia for it I suppose.)

**Comment by INFINI7I** [comment]
@gjgfuj what about integration?

**Comment by pitaapan** [comment]
Stadia, add Stadia too please 👍

**Comment by Primajin** [comment]
Yes, Stadia would be great. Also there is Mixaill/awesome-gog-galaxy#59

**Comment by mbanczerowski** [comment]
Aggregated in mentioned task.
