### ISSUE TITLE
Option to just open a game launcher.

### ISSUE THREAD

**Issue by scope-username** [gogcom/galaxy-integrations-python-api#123]
Would like to see an option of opening the game launcher(for example: Steam) by right clicking on the bookmark of the respective game launcher on the left side panel. At the moment, the only work around is to run/install a game and then quit the operation after the game launcher is opened. 

Thank you.

**Comment by mbanczerowski** [comment]
Hey. Thanks for suggestion. I think it such feature may be beneficial in some cases, but most of users won't use it. 

Tell us what is your use-case, why do you usually open Steam? And why do you think opening other launcher from Galaxy is better than opening it directly from Start Menu (Windows) or Finder (Mac)?

**Comment by scope-username** [comment]
It is a good-to-have feature as we would have access to open launcher from one place instead going for an extra step of looking/typing in Start Menu or Finder.

My personal use-cases would be - 

- Buying a game or Claiming a key

- Sending or Accepting friend requests

- Adding games to wish list / looking at wish list.

**Comment by mbanczerowski** [comment]
Thanks for your input. We'll consider adding such feature in API.

**Comment by mbanczerowski** [comment]
The API method is actually already added: https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.api.html#galaxy.api.plugin.Plugin.launch_platform_client

So I'm closing this feature request.

But still - Galaxy don't use that feature.

As far as I know, there was an idea to have an optional configuration (similar to checkbox for closing after game is finished) to launch other clients when GOG GALAXY starts, to make a quicker access to run games. But the idea was rejected for bringing little value and some problems (most of external clients already have "Open on system start" option opening all external clients could be heavy, people may forget that they set it already ect.).

If you think it is something to be added to GOG GALAXY:
- weather by opening selected clients on the GALAXY start
- or just having a dedicated button somewhere

please create a proposal via Cogwheel button -> Share feedback.
