### ISSUE TITLE
Please add Asmodee integration

### ISSUE THREAD

**Issue by n-t0r** [gogcom/galaxy-integrations-python-api#124]

**Comment by saitho** [comment]
Can you add more information on that?
What is Asmodee and where can we find it?

**Comment by ArtexJay** [comment]
They are a game publisher and they publish their games on Steam.

**Comment by saitho** [comment]
Why is the Steam integration not sufficient for that? :)

**Comment by mbanczerowski** [comment]
Aggregated in mentioned task.
