### ISSUE TITLE
Add Amazon Games support

### ISSUE THREAD

**Issue by Noelierx** [gogcom/galaxy-integrations-python-api#128]
Since Twitch Prime games can't be use anymore on the twitch desktop app, the plugin is now useless. 
All theses games can be downloaded and player on the Amazon Games client. 
Could you please add the support for the Amazon Games client?

**Comment by mbanczerowski** [comment]
Hi @Noelierx 
The plugin id is already available: https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md
