### ISSUE TITLE
Please add Google Play integration

### ISSUE THREAD

**Issue by INFINI7I** [gogcom/galaxy-integrations-python-api#129]
I have many games in Google Play and I want to see them in my library

**Comment by goldenmob72** [comment]
Ok, Now that would be super awesome!

**Comment by Primajin** [comment]
And Stadia would also be nice. Also there is https://github.com/Mixaill/awesome-gog-galaxy/issues/59

**Comment by mbanczerowski** [comment]
Aggregated in mentioned task.
