### ISSUE TITLE
push_cache overwrites credentials in database

### ISSUE THREAD

**Issue by UncleGoogle** [gogcom/galaxy-integrations-python-api#13]
Reproduction:

1) connect integration
2) _initialize_cache is called -> persistent_cache is w/o credentials
3) store_credentials notification is called -> Galaxy will put in integration db
4) `push_cache()` dumps local cache removing credentials

Galaxy should treat cache and stored_credentials separately.

**Comment by goggalaxy** [comment]
Quick fix in https://github.com/gogcom/galaxy-integrations-python-api/commit/9d9376286748b2d79c5bc0602a803114f223cbf6.

**Comment by UncleGoogle** [comment]
Woks as expected
