### ISSUE TITLE
Modify XBOX/Microsoft integration to show installables only...

### ISSUE THREAD

**Issue by Warrentheo** [gogcom/galaxy-integrations-python-api#131]
Hello, Loving Galaxy 2.0, Minor but useful tweak request, is it possible to add a switch to the XBOX integration that only shows titles that can be installed on PC?
When making a selection from the list, and pointing at the "Install" button, it will either take you to the relevant Microsoft Windows Store page to install it, or the "Install" button will be greyed out, and a popup tip on the "Install" button will show "Use your console to play this game"...

Since the plugin seems to already know if the game **can** be installed on the local environment or not, is it possible to restrict the list to only titles that can be installed?

**Comment by mbanczerowski** [comment]
Hi there. You may try to use `OS & consoles` filter and check `Windows`.

In the future please report bugs on Galaxy Mantis issue tracker available from cogwheel menu -> Report Issue.

Have a nice day!

**Comment by Bananaman** [comment]
Doing a custom bookmark with "Platform (Store): Xbox, OS: Windows, Status: Subscriptions" seems to work. At least it has filtered out a few of the Xbox games I had been fooled by earlier.

@mbanczerowski How reliable is the "OS: Windows" check? Can it **miss** some games that are made for Windows?

**Comment by mbanczerowski** [comment]
@Bananaman fairly reliable, never missed so far

**Comment by Bananaman** [comment]
> @Bananaman fairly reliable, never missed so far

Thank you, that's great to hear!

**Comment by Bananaman** [comment]
> @Bananaman fairly reliable, never missed so far

By the way, since I have a Xbox Game Pass Ultimate subscription, is this the correct configuration?

![image](https://user-images.githubusercontent.com/38923130/99411543-04a53800-28f4-11eb-8c3f-7044be4e4a80.png)

I have enabled "show subscription for Game Pass PC and Game Pass Ultimate", but did not enable Game Pass Console or Xbox Live Gold.

Is this correct for seeing all Ultimate subscription games?

**Comment by mbanczerowski** [comment]
@Bananaman Ultimate alone should be enough. If I remember correctly it is just a combination of PC and Console games.

**Comment by Bananaman** [comment]
> @Bananaman Ultimate alone should be enough. If I remember correctly it is just a combination of PC and Console games.

Ahh that makes perfect sense. Thanks a lot for the help! <3 I was confused because when I signed in, only "Xbox Live Gold" was pre-selected on its own. The auto-detection of my subscription didn't work. Anyway thank you, all is working well now with the OS platform filter! :)

**Comment by mbanczerowski** [comment]
I'm glad to help.

>  I was confused because when I signed in using the Galaxy plugin, only "Xbox Live Gold"
But - just to confirm, are you Xbox Live Gold subscriber?
