### ISSUE TITLE
Request: Please Allow 2nd Steam Accounts

### ISSUE THREAD

**Issue by DontBlnkBadWolf** [gogcom/galaxy-integrations-python-api#132]
I have 2 different Steam accounts with different games, and I would like the ability to have both accounts connected.

**Comment by Scaledish** [comment]
Why?

**Comment by DontBlnkBadWolf** [comment]
Why, what? That I am asking to allow 2 Steam Accounts? For the reason I stated.
Why, do I have 2 Steam Accounts? Because I can.

**Comment by mbanczerowski** [comment]
Hi, thanks for the proposal.

However I'm not sure if it is proper place to ask. Support for multiple accounts from one plugin OR running multiple integrations for one platform is not supported in Galaxy. If you send your feedback by Galaxy cogwheel menu -> Report Issue or Feedback. Reported feature requests are considered based on vote numbers.

**Comment by Scaledish** [comment]
> Why, do I have 2 Steam Accounts? Because I can.

Doesn't really motivate me to work on it

**Comment by DontBlnkBadWolf** [comment]
> 
> 
> > Why, do I have 2 Steam Accounts? Because I can.
> 
> Doesn't really motivate me to work on it tbh

Then don't. I just get tired of everyone asking why I have or do things the way I do. I don't feel the need to explain myself to anyone. Unless I choose to do so. Which is hardly ever.

**Comment by DontBlnkBadWolf** [comment]
> 
> 
> Hi, thanks for the proposal.
> 
> However I'm not sure if it is proper place to ask. Support for multiple accounts from one plugin OR running multiple integrations for one platform is not supported in Galaxy. If you send your feedback by Galaxy cogwheel menu -> Report Issue or Feedback. Reported feature requests are considered based on vote numbers.

Thank you, I had already done this but, it was around a day or two later that I discovered this to be in GitHub. So, I thought I'd take a stab at leaving one here. If it can't be done, then I'm not going to waste anymore thought on this. Another way would be to allow something like what Steam has and sharing games from family accounts on the same PC.

that's not something that I would call a deal breaker, I'll still use GOG. Have to since I've Pr-Ordered CP2077. I'll consider this topic closed.

**Comment by mbanczerowski** [comment]
> Another way would be to allow something like what Steam has and sharing games from family accounts on the same PC.

This could be potentially done in Steam community plugin as a support for steam sharing: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/12

**Comment by schmurtzm** [comment]
> This could be potentially done in Steam community plugin as a support for steam sharing: [FriendsOfGalaxy/galaxy-integration-steam#12](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/12)

Thanks, multiple steam accounts working perfectly with family sharing.
