### ISSUE TITLE
Request: Amazon Games launcher integration 

### ISSUE THREAD

**Issue by anhonorableleech** [gogcom/galaxy-integrations-python-api#136]
Ability to add from Amazon Games?

**Comment by jashazzard** [comment]
I would also Like to have the amazon games launcher game collection integrated please.

**Comment by JanPokorny** [comment]
The right place to request integrations is here: https://github.com/Mixaill/awesome-gog-galaxy/issues

**Comment by anhonorableleech** [comment]
Thank you @JanPokorny. Issue moved: https://github.com/Mixaill/awesome-gog-galaxy/issues/84
