### ISSUE TITLE
Please add Itch.io Support

### ISSUE THREAD

**Issue by RoY7x** [gogcom/galaxy-integrations-python-api#137]
Pretty simple. Please consider adding Itch.io indie games to be apart of the sync'ed list through GOG Galaxy.

**Comment by goldenmob72** [comment]
That would be Nice :)

**Comment by Mixaill** [comment]
https://github.com/Ertego/gog-galaxy-itch.io

**Comment by JanPokorny** [comment]
The list of all available "unofficial" integrations is here: https://github.com/Mixaill/awesome-gog-galaxy

Note that the ones that can be installed from Galaxy itself are marked with "✅" in the "In built-in search" column. These ones are checked by @FriendsOfGalaxy. The rest is "unofficial-unofficial" and needs to be installed manually.

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.
