### ISSUE TITLE
About Nintendo Intergration 

### ISSUE THREAD

**Issue by goldenmob72** [gogcom/galaxy-integrations-python-api#139]
Wouldn't it be easier to just link the Nintendo Account instead ? Because, It should show all the games that the person if the person owns if he/she Buys game using that Account
I was able to Link/Connect my other Game Accounts to my Nintendo Account

![Screenshot_1](https://user-images.githubusercontent.com/40510344/79746974-e2edbf00-82d8-11ea-89f9-902fb53db773.png)

**Comment by bizzl-greekdog** [comment]
That would work, if the Nintendo Account API actually lists games from linked accounts. But then you wouldn't get the deduplication.
What you would definitively not get would be some kind of forwarding or synchronization of the actual links, as that would be a breach of security (and of most API EULAs, probably)

**Comment by goldenmob72** [comment]
then GOG would have to Contact Nintendo

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.

You can also propose official integrations in the general feedback [form](https://docs.google.com/forms/d/e/1FAIpQLSfa__KDaxbFseSOFz2ic-XGfIfb7RSbBo4aiXKfgj5Al5EzDw/viewform).
