### ISSUE TITLE
Get platform list up-to-date

### ISSUE THREAD

**Issue by JanPokorny** [gogcom/galaxy-integrations-python-api#140]
During the creation of https://github.com/AB1908/GOG-Galaxy-Export-Script/, it was discovered (https://github.com/AB1908/GOG-Galaxy-Export-Script/pull/12) that there are some platforms supported by GOG Galaxy 2.0, but not included in the list here: https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md

Namely the discovered ones were:
- fxstore
- generic
- gamesessions
- gog
- indiegala
- minecraft
- nuuvem
- oculus
- playfire
- rockstar
- twitch

Some of these even have their own integrations created, so I believe the case is that the list is just out-of-date. Please consider updating the list.

(I understand that some, like "gog" and "generic", are not included intentionally, but please consider including them too for the sake of tools like the one mentioned above.)

**Comment by JanPokorny** [comment]
To add, there also seem to be "test" and "unknown", judging by https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py#L4

**Comment by goldenmob72** [comment]
Playfire moved to Green Man Gaming

**Comment by JanPokorny** [comment]
@JanPokorny It's still in the code, so it should be documented: https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py#L4

**Comment by mbanczerowski** [comment]
Missing ids added, thanks for reporting!
`generic` is internal id for games added manually in GOG Galaxy and won't work from plugins.
