### ISSUE TITLE
PSN Login does not work for me - A connection to the server could not be established.

### ISSUE THREAD

**Issue by dimmduh** [gogcom/galaxy-integrations-python-api#144]
![image](https://user-images.githubusercontent.com/446814/81525604-d57f9e00-9387-11ea-9552-52a45ef1fc75.png)

**Comment by exoscoriae** [comment]
same issue

**Comment by ringtailedfox** [comment]
same here!  i thought I was the only one!

**Comment by HeRoSomeguy** [comment]
The PC PSN app does not work in every region. So I would check that it works in your region first

**Comment by exoscoriae** [comment]
Used to work for me. My region is North America (US), which is unlikely to not be supported.

**Comment by Raynevun** [comment]
Same problem
Region eu/pl
I think it might be related to enabled 2-Step Verification

**Comment by dimmduh** [comment]
It's seems to fixed for me. From RU now works.

**Comment by exoscoriae** [comment]
I was about to comment that I thought it was 2-step verification as well. If I log in through their website, it sends me a text message. If I log in through galaxy, it does one of those damn "choose the right picture" captures. Then it claims the server times out.|

So while the actual error has changed from "connection could not to establish" to "server timed out", I still can not connect.

**Comment by Raynevun** [comment]
Works for me now too.
With 2-Step Verification.
Region EU/PL

**Comment by tobiasbalzano** [comment]
I'm having this issue, tried enabling 2-step which didn't work
Region EU/SE

**Comment by ringtailedfox** [comment]
it's finally working for me... my location is Canada... not sure what changed, but I can finally log in with it again :D

**Comment by Cris3po** [comment]
I figure out something that worked for me. Can I put external links here? On this website there is a step by step that worked in my case (remember to copy and rename the original file on other fold - just in case) https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_network_was_unable_connect/page15
![Step by step](https://user-images.githubusercontent.com/67075943/84951223-80d9ec00-b0c6-11ea-81ed-f4003646458a.PNG)

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues
