### ISSUE TITLE
Playstation Network integration doesn't work : Connexion Timeout.

### ISSUE THREAD

**Issue by SamirAcF** [gogcom/galaxy-integrations-python-api#147]
I don't know when it exactly occured, but i cannot link Playstation Network anymore. 

My GOG Galaxy version is 2.0.15
My computer runs Win 10 Pro 2004 release 19041.264

**Comment by Gravesy83** [comment]
Same issue as above user, hadn't used GOG Galaxy before so can't tell when this issue was introduced.
Connection to PSN times out after entering password and completing the CAPTCHA.
CAPTCHA verifies succesfully, but then the error pops up stating that the connection has timed out.

GOG Galaxy version is 2.0.15.43 beta
System runs Windows 10 Home build 18368.836

**Comment by cedricbrice** [comment]
Same here.
GOG Galaxy version is 2.0.15.43 beta
System runs Windows 10 Pro build 18368.836

Worth noting that it is possible to connect using Chrome, but not using Brave nor Mozilla (on the same computer) and that the 2FA is activated on my account although GOG Galaxy doesn't trigger it.

**Comment by SamirAcF** [comment]
Looks like it's repaired for me (i've done nothing for). 

GoG galaxy version : 2.0.15.43

**Comment by cedricbrice** [comment]
Well that was only for then.

Just tried it and no 2FA, slow captcha and connection timeout

**Comment by mbanczerowski** [comment]
@cedricbrice 

> Worth noting that it is possible to connect using Chrome, but not using Brave nor Mozilla (on the same computer) and that the 2FA is activated on my account although GOG Galaxy doesn't trigger it.

What version of Brave nor Mozilla do you use?

**Comment by cedricbrice** [comment]
Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

For some reason I managed to log in using GOG Galaxy 2.0 yesterday without it asking for a 2FA (while it is active on my account)
