### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Pratilectron** [gogcom/galaxy-integrations-python-api#151]
Uplay plugin keeps crashing after few seconds of connecting.
Message code : "**Plugin has crashed. Retry.**"

![PDDX2Fb](https://user-images.githubusercontent.com/32908032/84348626-51e6e600-abad-11ea-94cb-3bc27ff43105.png)

**Comment by Zatsando** [comment]
this is a common issue not only with uplay (in my case with steam). try to disconnect and then reconnect.

**Comment by piroko13** [comment]
It's happening with the Epic Games plugin too

**Comment by eaglet123** [comment]
This is still happening. I tried Steam, Uplay, and Origin.

**Comment by roughnecks** [comment]
I'm getting this with Steam and even if I close Galaxy, I can see the python process in Task Manager taking up CPU resources.

Also, while scanning my Library. the % of games detected goes up and down randomly and never stops.

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues
