### ISSUE TITLE
I only can connect xbox live and gog. no steam no epic no psn no uplay

### ISSUE THREAD

**Issue by tommyonsn** [gogcom/galaxy-integrations-python-api#152]
I only can connect xbox live and gog. no steam no epic no psn no uplay, 
no other platforms, only gog and xbox live.

**Comment by CodeForBug** [comment]
+1

**Comment by scopgu** [comment]
me too

**Comment by AgClKawauso** [comment]
me too

**Comment by fedprod** [comment]
Use the search function?
https://i.imgur.com/vQowGlA.png

**Comment by AgClKawauso** [comment]
It still can't work whether I use search or not

**Comment by fedprod** [comment]
No clue then, maybe some APIs down?

**Comment by mbanczerowski** [comment]
Hi, please report on https://mantis2.gog.com/. Attach logs.
