### ISSUE TITLE
Unusual UI and can't connect to steam

### ISSUE THREAD

**Issue by Ricky816845** [gogcom/galaxy-integrations-python-api#153]
![QQ截图20200616222228](https://user-images.githubusercontent.com/20158450/84787422-8977e700-b020-11ea-82db-cf0d7cbc6ae7.png)

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.
