### ISSUE TITLE
cannot bind to other platforms

### ISSUE THREAD

**Issue by shao12781566** [gogcom/galaxy-integrations-python-api#154]
like this
![360截图20200616232129531](https://user-images.githubusercontent.com/57243196/84794131-75d07e80-b028-11ea-89fe-b6118c2fcb51.jpg)

**Comment by eaglet123** [comment]
Same here.

**Comment by shao12781566** [comment]
I know. 
Just turn off your firewall

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues
