### ISSUE TITLE
Playstation integration issue ⭐ | Solved ✔️

### ISSUE THREAD

**Issue by tonydimasi** [gogcom/galaxy-integrations-python-api#155]
I tried to connect to my Playstation account to have integration with the platform, but every time i try to enter it gives me an error "The connection to the server timed out.
"
I have already checked my credentials and I can log in via my PS4 console and through a browser, the problem occurs with Gog Galaxy. Thank you

![Annotazione 2020-06-16 172051](https://user-images.githubusercontent.com/21182574/84795409-bc59b500-aff7-11ea-9768-b6f5959e1bd4.png)

**Comment by VictorMarc1997** [comment]
+1
Same issue happening with the windows firewall turned off

**Comment by LiberalTugboat** [comment]
+1
It is also blocking Uplay integration login since I use my PSN login for Uplay.

**Comment by tonydimasi** [comment]
> +1
> It is also blocking Uplay integration login since I use my PSN login for Uplay.

Meh, you know what a coincidence when everything returns to normal after June 23, casually after the promo of the witcher 3.

**Comment by TomasPvL** [comment]
+1
Happening to me too

**Comment by cicisse** [comment]
same issue for me too

**Comment by phelipepalte** [comment]
+1
Same here

**Comment by tonydimasi** [comment]
Update N.1
After the first report I received this message and the ticket was marked as resolved.

![AnnotazioneGog](https://user-images.githubusercontent.com/21182574/84818376-b32c1080-b016-11ea-80e4-a03980686854.png)

.

**Comment by tonydimasi** [comment]
Update N.2
All other platforms are connected without problems.

![ScreenGog](https://user-images.githubusercontent.com/21182574/84820148-7281c680-b019-11ea-8019-fba38cdcbf6f.jpg)

**Comment by dsowza** [comment]
https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_network_was_unable_connect/page8 has a tip about what can be done. Maybe it can help to fix it in the code.

The workaround works.

**Comment by tonydimasi** [comment]
> https://www.gog.com/forum/general_beta_gog_galaxy_2.0/playstation_network_was_unable_connect/page8 has a tip about what can be done. Maybe it can help to fix it in the code.
> 
> The workaround works.
> 
> I think the solution is to use an external browser to authenticate instead of an embedded one.

Thank You, i'll summarize it and make it as simple as possible:

 log in to PSN (store.playstation.com) through your browser

- after the login open this link: https://ca.account.sony.com/api/v1/ssocookie
Copy content of "npsso"

- open windows explorer and enter the following into the address bar at the top and press enter
%LocalAppData%\GOG.com\Galaxy\plugins\installed\

- open the psn_{random number} folder and edit the plugin.py file with your favourite text editor

- go to line 64 and change it from:
stored_npsso = stored_credentials.get("npsso") if stored_credentials else None

to:
stored_npsso = "Copied value of npsso" (just this, neither if stored_credentials else None")

("copied value of npsso" should be a 64 character long text consisting of numbers, lower case letters and upper case letters)
(the quotation marks " " are important!)

for example: 

async def authenticate(self, stored_credentials=None):
        stored_npsso = "here the value from https://ca.account.sony.com/api/v1/ssocookie"

- restart GOG Galaxy
- try connecting with PSN again

**Comment by FriendsOfGalaxy** [comment]
Plugin dev here. If you really want to do that, the changed line should be:

`        stored_npsso = stored_credentials.get("npsso") if stored_credentials else "<your_npsso_here>"`

This way you won't be logout after Galaxy restart, when npsso got changed.

**Comment by tonydimasi** [comment]
> To keep connection between Galaxy restarts, changed line should be:
> 
> ` stored_npsso = stored_credentials.get("npsso") if stored_credentials else "<your_npsso_here>"`

Thank you 🤙🏻

**Comment by scyto** [comment]
This is not solved as in fixed, it is a flawed workaround as you don't know when that token will be rotated (unless sony are too stupid to rotate their tokens...). Please don't close this until there is a fix.

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues
