### ISSUE TITLE
It's possible add Itch.io?

### ISSUE THREAD

**Issue by peter9811** [gogcom/galaxy-integrations-python-api#156]
I try search on Galaxy, and I can't see it

**Comment by tombuben** [comment]
There are multiple iftch.io plugins already, such as https://github.com/Ertego/gog-galaxy-itch.io or https://github.com/tauqua/gog-galaxy-itch.io

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report your issue
