### ISSUE TITLE
PSN Offline

### ISSUE THREAD

**Issue by NeXtOblivion** [gogcom/galaxy-integrations-python-api#157]
I entered the code to fix the problem that did not allow me to connect to the PSN but now it tells me that it is offline... what can I do?

**Comment by Cris3po** [comment]
Same problem here. All other platforms loged in. PSN saying that it's offline.

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.
