### ISSUE TITLE
Adding new platform IDs at least for platforms where integrations already exist

### ISSUE THREAD

**Issue by micpp42** [gogcom/galaxy-integrations-python-api#159]
Hi,
So on the Awesome GOG Galaxy page there are a couple of integrations listed where they've essentially picked an arbitrary platform ID to use, since there's no correct one built in.
The ones listed on the page are osu (using the Newegg platform ID), Touhou/thcrap (using the Testing purposes platform ID), ScummVM (using the Amiga plaform ID), PS3 (using the Colecovision platform ID), and DosBox (using the Atari Jaguar platform ID)
Link to the list for reference: https://github.com/Mixaill/awesome-gog-galaxy
Would it be possible to add new platform IDs to cover these platforms?
Thanks.

**Comment by mbanczerowski** [comment]
Thanks for raising the issue. I've put those into #160
