### ISSUE TITLE
Steam connection possibly causing failed login attempts

### ISSUE THREAD

**Issue by DoktorvonZwitter** [gogcom/galaxy-integrations-python-api#170]
So a couple days ago I was grappling with a series of "failed login attempts" while I was still logged into Steam. At some point I decided to disconnect Galaxy from it to help the timeout progress. Lo and behold, for the next few days, Steam ran wonderfully, no error messages about "failed logins."

I reconnected it again today and what do I get while I'm already signed into Steam after a while? Another "failed login" error message. It seems Steam doesn't like the connection to Galaxy.

**Comment by mbanczerowski** [comment]
Closing as Steam community plugin is not related to this repository.

**Comment by DoktorvonZwitter** [comment]
What is it related to then?

**Comment by mbanczerowski** [comment]
Steam integration is community plugin in the separate repo. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose

**Comment by DoktorvonZwitter** [comment]
Thanks.
