### ISSUE TITLE
Steam suspends my account for 30 minutes if I connect on multiple devices

### ISSUE THREAD

**Issue by erictbar** [gogcom/galaxy-integrations-python-api#171]
Trying to connect to Steam on multiple Macs and PCs within GOG Galaxy leads to disconnections in GOG Galaxy, and when I open Steam I see "could not connect to the Steam network" until my account is unlocked in about 30 minutes.

Steps  to  reproduce:
1.  Be logged into Steam on GOG Galaxy on PC running Windows 10 20H2. Have the app open
2. Connect Mac running macOS Big Sur 11.0.1 to Steam via integrations on GOG Galaxy. 

Results: Receive error asking me to retry to connect to Steam. Clicking on the link does nothing. Disconnect from Steam. Reconnect, correctly enter password, attempts to connect, does not get to asking me for 2FA, says connection... and spinning wheel. Eventually Steam will show as "Offline. retry." But with an option to disconnect.
Open Steam. receive error "could not connect to the Steam network." 30 minutes later, able to reconnect to Steam

This issue has occurred for a long time, I have tried reporting it directly to GOG. Occurs when I use GOG a lot on the 2 devices, which I don't do that often. Sometimes I will notice my library will be smaller on both devices, with only a handful fo Steam games in it, before I try to reconnect.

**Comment by mbanczerowski** [comment]
Hi @erictbar that sounds as a serious issue. Unfortunately Steam integration issue is the unofficial, community integration so we cannot help you directly. If think there is already related issue o steam integration github: https://github.com/FriendsOfGalaxy/galaxy-integration-steam
