### ISSUE TITLE
Any chance for a Prime Gaming integration?

### ISSUE THREAD

**Issue by Vadatajs** [gogcom/galaxy-integrations-python-api#172]
I couldn't find where to leave a request, sorry if this is the wrong place for it.

Twitch's Prime Gaming is owned by Amazon now, just wondering if there's an integration possibility there. It would be really great.
Also Discord has their own game service that would be great to integrate as well

Thanks!

**Comment by mbanczerowski** [comment]
You can find it there: https://github.com/Mixaill/awesome-gog-galaxy
