### ISSUE TITLE
Origin integration doesn't detect uninstalled games

### ISSUE THREAD

**Issue by haikupaiku** [gogcom/galaxy-integrations-python-api#174]
**Problem**
After uninstalling a game on Origin, the game still appears as installed in Galaxy.

**Alternatives**
At the moment I can hide the games from the library, but it's not ideal.

**Comment by ShaunV2** [comment]
Not having this issue at all.

**Comment by haikupaiku** [comment]
I'm not saying it happens in all cases, but it's happened with me: I currently have 3 games appearing as installed in Galaxy that aren't installed (Battlefield 4, Battlefield Hardline, and The Sexy Brutale).

I'm not the first person to come across this problem either: https://www.gog.com/forum/general_beta_gog_galaxy_2.0/uninstalled_game_still_appears_as_installed_origin_game

I've tried resetting the integration, but they still appear as installed.

**Comment by mbanczerowski** [comment]
@haikupaiku looks like the plugin problem. Please report the issue in here: https://github.com/FriendsOfGalaxy/galaxy-integration-origin
