### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by Stevoisiak** [gogcom/galaxy-integrations-python-api#18]
Is there a publicly declared license for this library?

The README includes [a brief legal notice](https://github.com/gogcom/galaxy-integrations-python-api/blob/f4bd18a8ab5d71181810dbc842e3b079c2744ed1/README.md#legal-notice) about developers requiring all rights to create integrations, but [a missing license](https://opensource.stackexchange.com/a/5874/7777) means that custom integrations might not have permission to modify or redistribute this Python library.

**Comment by apaulouski** [comment]
Done. Thanks for your help.
