### ISSUE TITLE
Bethesda connect directs to main page 

### ISSUE THREAD

**Issue by heavyoak** [gogcom/galaxy-integrations-python-api#182]
**Problem**
when using the Bethesda connect after login it directs to the main page of Bethesda.com and doesn't complet the connect action.

**Comment by dloder** [comment]
I have the same issue.

**Comment by NiksaVel** [comment]
same issue

**Comment by VladanDrapela** [comment]
Had the same problem for days, but now it's working again.

**Comment by webknows** [comment]
This issue seems resolved for me as well now

**Comment by Danyelalejandro** [comment]
Me too, it worked today. Last year was the same. It seems Bethesda changes something about how we login near a Quakecon....
