### ISSUE TITLE
Remove never connected integrations.

### ISSUE THREAD

**Issue by ThunderOne1** [gogcom/galaxy-integrations-python-api#185]
I'd like to get this feature as for instance I tried to connect to some integrations like Final Fantasy XIV, Wargaming... despite I don't have an account on them, now they keep appearing and can't remove them because I never connected.

I tried uninstalling and reinstalling but it didn't work, they keep appearing.

**Comment by mbanczerowski** [comment]
Hi @ThunderOne1 
thanks for feedback, I agree that it could be useful. Please share the idea using `Share feedback` from Galaxy cogwheel menu.

For now you can remove additional integrations from the list by removing them from the lookup directory https://github.com/gogcom/galaxy-integrations-python-api#lookup-directory
