### ISSUE TITLE
Milestones with too much space 

### ISSUE THREAD

**Issue by Pab10Suarez** [gogcom/galaxy-integrations-python-api#187]
**Problem**
_this is how it appears in activity feed_
![image](https://user-images.githubusercontent.com/29072142/134606693-71bff848-cbee-405e-ab71-f49ddfdf384b.png)

_and this is how it appears in gog galaxy "profile"_
![image](https://user-images.githubusercontent.com/29072142/134606706-e8960078-685d-43f0-84c6-16a4032dbce0.png)

_it seems to be an icon problem because the text isn't missing, the icon part seems to be large than it should be
(also thx for opening issues i'd like to help!)_
from:
https://github.com/jshackles/RetroGOG/issues/5#issue-739524149

update:
i was looking around and almost a year ago i thought it was just one integration bug but since my sister started playing on cemu i'vseen this error is there too (integration: https://github.com/LeonardFiedrowicz/galaxy-integration-cemu)
![image](https://user-images.githubusercontent.com/29072142/134606848-6533552b-9535-443a-8ee6-8fc485f1a9e9.png)

maybe related? (no icon ) (gamecube integration https://github.com/JTNDev/galaxy-integration-gc) 
![image](https://user-images.githubusercontent.com/29072142/134606943-1b10c6c5-829e-44bc-8284-625640fe5f9f.png)

pd: i guess it's somehting with the api or maybe with galaxy itself since i'm not sure i report it here but i will remove it if this is not the place

**Comment by mbanczerowski** [comment]
It is related to Galaxy itself - report please using Galaxy cogwheel menu - Report issue.

To be honest I don't understand where is the problem, so consider adding an additional bigger screenshot (that includes Galaxy filters so someone can reproduce) and point out what is buggy with red mark.
