### ISSUE TITLE
List of available integrations

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#20]
I think it would be useful to keep a list of the existing integrations somewhere.

**Comment by apaulouski** [comment]
We're aware of lack of user-friendly integrations search and will get back to this once core features are complete. This is not a top-prio as most plugins are available right after GXL is installed.
Until then such a list could do, yet I'm not sure how many users will actually find this page :)

**Comment by Mixaill** [comment]
Added 
* Bethesda.net by @TouwaStar
* Humble Bundle by @UncleGoogle

**Comment by UncleGoogle** [comment]
Thanks for linking. @Mixaill maybe create a gist or separate repo with this? It's easier to edit by others

**Comment by fonsosm** [comment]
Humble Bundle works?

**Comment by Danyelalejandro** [comment]
Guys. Someone please help. Twitch game library (that could be opened via PC Twitch app) is not included yet, but their game library is even bigger than Epic's. They sold games a while ago and they are giving free games every month to Twitch prime members, so their library keeps increasing.
Their games are DRM as GOG and Epic.
Please, someone who knows about programming and has access to this tools and GOG galaxy 2.0 beta, help us

**Comment by nyash-qq** [comment]
@Danyelalejandro If no one will take care of it until next weekend, I'll try to do it. 
PS: GOG games are DRM-free actually

**Comment by Mixaill** [comment]
@UncleGoogle I've created a separate repo https://github.com/mixaill/awesome-gog-galaxy

**Comment by Danyelalejandro** [comment]
Hello guys. If someone is working on development of Twitch integration, it should be highly recommended to check the dll extension of Playnite for this: https://github.com/JosefNemec/Playnite/releases
Maybe it has the key to develop it as well in GOG Galaxy 2.0. Thank you all

**Comment by apaulouski** [comment]
Supported integrations can now be searched in the GLX settings view
