### ISSUE TITLE
Twitch is missing from the Platform ID List

### ISSUE THREAD

**Issue by RelativeProgramming** [gogcom/galaxy-integrations-python-api#21]
I just noticed this. I'm not sure, if that is intentional or not.

**Comment by apaulouski** [comment]
Some platforms might be missing from the list. We'll add them eventually.

**Comment by Danyelalejandro** [comment]
Please include Twitch game library integration. Their library is even bigger than Epic's. Please help.

**Comment by dpmcg89** [comment]
Please add this.  I have a ton of games on Twitch.

**Comment by Itay080** [comment]
I'd love to see a Twitch integration as well :)

**Comment by Danyelalejandro** [comment]
Hello guys. If someone is working on development of this integration, it should be highly recommended to check the dll extension of Playnite for this Twitch integration: https://github.com/JosefNemec/Playnite/releases
Maybe it has the key to develop it as well in GOG Galaxy 2.0. Thank you all

**Comment by WeiliiEyedWizard** [comment]
Id love twitch integration. Please add

**Comment by matrixraven** [comment]
On board with wanting Twitch integration, please and thank you! I keep getting free games every month from Twitch Prime, many I don't have anywhere else.

**Comment by rgardnercook** [comment]
I would also love Twitch integration! There are quite a few solid games in my Twitch library, but it's a pain to see them with the current twitch client.

**Comment by RelativeProgramming** [comment]
Well, there actually exists one now. You can find it here:

https://github.com/Mixaill/awesome-gog-galaxy

Note, that it temporarily uses Amazon as its platform ID.

**Comment by dpmcg89** [comment]
> Well, there actually exists one now. You can find it here:
> 
> https://github.com/Mixaill/awesome-gog-galaxy
> 
> Note, that it temporarily uses Amazon as its platform ID.

That's awesome.  I'll test it out later today.  Thanks for the heads up.

**Comment by johny-gog** [comment]
We'll be adding Twitch to list of possible platforms IDs most probably in the next update.

**Comment by Mixaill** [comment]
Added in https://github.com/gogcom/galaxy-integrations-python-api/commit/8d6ec500f97e74efd709902cad2447dafc1b7397

**Comment by apaulouski** [comment]
Please keep in mind, all platforms added in 8d6ec50 will only be supported by the Galaxy Client with the next update.

**Comment by Birdlawyerr** [comment]
oh yes Plz add twitch integration.

**Comment by apaulouski** [comment]
Finally supported by the client :)
