### ISSUE TITLE
Add "no-platform" games

### ISSUE THREAD

**Issue by m4gnify** [gogcom/galaxy-integrations-python-api#24]
For example Minecraft, or Warcraft III.

(direct add exe's?)

**Comment by apaulouski** [comment]
"Warcraft III" shall be managed by the battle.net platform, while Minecraft is either winstore or its own platform.
I'm not sure what exactly you are asking about. Could you elaborate?

**Comment by m4gnify** [comment]
Warcraft III is not on the Battle.net launcher, and those games were just examples. There are a lot of games, specifically older games, that don't have a launcher like Steam or Uplay. I would like the possibility to add them directly, not just launcher games.

**Comment by p1c2u** [comment]
@m4gnify Isn't it 'Generic' platform id atm? There should be more specific platform id, based on OS like Microsoft Windows, Linux, MacOS.

**Comment by apaulouski** [comment]
'Generic' was added for test purposes only, until support for actual platform is added. 
The option to manually add games and link them with executable files is not yet available in the GLX2.0 itself, Although it might be done via plugins, it wasn't supposed to be done like that.

**Comment by Qberty21** [comment]
Where can I find such an addition?

**Comment by apaulouski** [comment]
This is now a basic functionality in the Galaxy Client.
