### ISSUE TITLE
track play time even if the native launcher doesn't support it

### ISSUE THREAD

**Issue by RelativeProgramming** [gogcom/galaxy-integrations-python-api#25]
I don't know, if this is the right place for such an request, but it would be nice if games from a launcher like the Epic Games Store were tracked by GOG Galaxy.

**Comment by apaulouski** [comment]
Hey. Thanks for your proposal. We might consider adding this feature in the future, once we finish with core functionality (more cool stuff coming soon).
Would be cool if in this repo we keep only issues/requests related to the integrations API so it's easier to manage stuff. General feedback and GLX features requests can be sent via GLX -> cogwheel -> Share Feedback.

**Comment by RelativeProgramming** [comment]
ok, thank you.
