### ISSUE TITLE
possibility to define source icon in plugins

### ISSUE THREAD

**Issue by RelativeProgramming** [gogcom/galaxy-integrations-python-api#26]
![image](https://user-images.githubusercontent.com/16016861/61550632-42215900-aa53-11e9-8b9d-c0101ff94516.png)
![image](https://user-images.githubusercontent.com/16016861/61550643-4a799400-aa53-11e9-8c1c-8a41dce7ac53.png)

**Comment by UncleGoogle** [comment]
Those comes from`humble` plugin. I suppose they are hardcoded, so please design icons for all listed platforms. Thanks!

**Comment by apaulouski** [comment]
Thanks for reporting this. Unfortunately not all platforms are fully supported yet, but we will add those icons in the future.

**Comment by UncleGoogle** [comment]
Just for reference:
https://commons.wikimedia.org/wiki/File:Humble_Bundle_H_logo_red.svg
https://github.com/FortAwesome/Font-Awesome/issues/4684
https://support.humblebundle.com/hc/en-us/articles/202742060-Bundle-Logos

I'm not sure if the "bag" icon should be used or "H".  IM(H)O, The first fits better for Galaxy purposes, but the latter is in official resources.

**Comment by apaulouski** [comment]
Missing icons for any new platforms should be reported to the GOG via the GLX with cogwheel menu -> Report Issue
