### ISSUE TITLE
My GOG plugin doesnt show up

### ISSUE THREAD

**Issue by mdrokz** [gogcom/galaxy-integrations-python-api#27]
Hello im trying to integrate my plugin to gog using platforms.generic but its not showing up i even restarted client and clicked on refresh integrations and also is the client supposed to run the plugin.py script or i need to manually run it? if i manually run i get an error like this.
![image](https://user-images.githubusercontent.com/33598169/61593199-0bd20e00-abfa-11e9-9c98-553a17656c20.png)
and also this is my manifest.json and code.
![image](https://user-images.githubusercontent.com/33598169/61593202-2efcbd80-abfa-11e9-9b38-efa696b1fe28.png)
![image](https://user-images.githubusercontent.com/33598169/61593206-3ae87f80-abfa-11e9-98f5-73361d0a1741.png)
![image](https://user-images.githubusercontent.com/33598169/61593210-43d95100-abfa-11e9-883a-bb2a3f261f1d.png)
Thanks for reading. please try to help me

**Comment by apaulouski** [comment]
Hey. Your plugin looks fine. Not all platforms are fully supported yet.

**Comment by mdrokz** [comment]
> Hey. Your plugin looks fine. Not all platforms are fully supported yet.

Oh Okay one more question is plugin.py manually run from command line or its run from GOG client?

**Comment by Mixaill** [comment]
@apaulouski 

There is list of IDs which are handled in the source code but not displayed in the UI
* generic
* other
* unknown

**Comment by Mixaill** [comment]
>Oh Okay one more question is plugin.py manually run from command line or its run from GOG client?

GOG Galaxy automatically run it via `<GOG_DIR>/python/python.exe <path_to_script> <port number> <token>`

**Comment by mdrokz** [comment]
> > Oh Okay one more question is plugin.py manually run from command line or its run from GOG client?
> 
> GOG Galaxy automatically runs integration via `<GOG_DIR>/python/python.exe <path_to_script> <port number> <token>`

Oh Okay so how would i run a generic plugin script through GOG galaxy?

**Comment by Mixaill** [comment]
Well, looks like the only possible way is to change `generic` to something supported like `winstore`.

**Comment by mdrokz** [comment]
> Well, looks like the only possible way is to change `generic` to something supported like `winstore`.

Ah i see,Ok and anyway to catch errors my plugin always crashes when i change it to something like itch.io or steam. im using the same code as in the image provided.

**Comment by Mixaill** [comment]
You can find logs in the `C:\ProgramData\GOG.com\Galaxy\logs\plugin-<plugin_type>-<plugin_guild>.log`

**Comment by mdrokz** [comment]
> You can find logs in the `C:\ProgramData\GOG.com\Galaxy\logs\plugin-<plugin_type>-<plugin_guid>.log`

Awesome,Thanks alot man and thanks for helping me so fast. 👍 😄

**Comment by ivellios** [comment]
I have similar issue. I changed `generic` to `winstore` or `humble`. In both cases the plugin shows up, but cannot connect (`Failed to start`). How can I debug on MacOS? Where will I find logs for my plugin?
