### ISSUE TITLE
Incorrect game_times feature detection

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#28]
Game Times feature requires `get_games_time` function overriding ( https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/plugin.py#L157 ), 

but it looks like it should be `import_game_times`.

**Comment by apaulouski** [comment]
`get_game_times` is a part of the `galaxy.api.plugin.Plugin` interface, while `import_game_times` is a JSON-RPC method it handles. Note `get_games_time` is deprecated and will be replaced soon with transaction-like `start_game_times_import`. Similarly `get_unlocked_achievements` will be replace by the `start_achievements_import`

**Comment by Mixaill** [comment]
It looks like it already replaced with `start_game_times_import`, but `get_games_time` still in use for feature detection.

**Comment by apaulouski** [comment]
Correct. It's left for backward compatibility, but will be cleaned up soon™.

**Comment by apaulouski** [comment]
Fixed in 0.45 (e33dd09)
