### ISSUE TITLE
Steam controller integration

### ISSUE THREAD

**Issue by Tramort** [gogcom/galaxy-integrations-python-api#29]
I have steam controller and I want run games from other platform with it.
System don't recognize steam controller as controller by default, it require run game via steam.
There are some "hacks",for example, [GloSC](https://alia5.github.io/GloSC/) and other, but they are not enought convinient to use.
It would be cool to have ability somehow intergretate it to gog galaxy.

**I don't talk about full intergartion of some solution to galaxy but it would be good have some integration points.** For example, game pre-run command (separetly for every games/platform) in game settings or via plugin.

**Comment by apaulouski** [comment]
Thanks for your feedback.
Although the idea sounds cool, let's keep GitHub "issues" only related to the python integrations API.
You can send general feedback via GLX: cogwheel menu -> Share Feedback

**Comment by Tramort** [comment]
ok, sorry to bother you

**Comment by apaulouski** [comment]
No problem. We glad you like it ;)
