### ISSUE TITLE
Open internal browser method

### ISSUE THREAD

**Issue by UncleGoogle** [gogcom/galaxy-integrations-python-api#33]
Hi,

please add a method to open internal browser.

```
async def open_internal_browser(self, url, cookies=None, js=None)
```
For humblebundle plugin this would be useful to open `keys` page for logged-in user where you can redeem your games for other platforms like Steam. [hb issue](https://github.com/UncleGoogle/galaxy-integration-humblebundle/issues/6)

Furthermore, this will allow to avoid plugin authors to code its owned GUI's ([hb issue](https://github.com/UncleGoogle/galaxy-integration-humblebundle/milestone/1)), and even run webrowser games (?)

**Comment by apaulouski** [comment]
If a plugin needs a browser functionality, the best would be to redirect the user to the system browser. This would be both safer, more transparent and convenient for the user, as he might already have his accounts logged there, passwords saved, extensions installed etc. 
The idea behind internal browser was to keep it isolated, small and lean, and server a single purpose: open a page and give back all its content. While with what you suggest we'll end up re-implementing a whole browser inside the GLX.

**Comment by UncleGoogle** [comment]
Thanks, I understand the security reasons. I'll open default browser instead.
