### ISSUE TITLE
Support for multiple launchers

### ISSUE THREAD

**Issue by Valkian24** [gogcom/galaxy-integrations-python-api#39]
There's a few other launchers that I feel that should also be included other than Steam, Epic, Uplay, Origin and the consoles (Xbox and Playstation).

I'm suggesting the Blizzard app, the Microsoft Xbox hub on PC, the Bethesda launcher and Twitch.

It'd be great to have them listed to keep track of.

**Comment by Danyelalejandro** [comment]
I agree, specially with Twitch game library supoort

**Comment by Ellathar** [comment]
As a XBox Game Pass Ultimate subscriber, I can't agree more when it comes to the Xbox Hub. Same goes for Twitch, as I have many games there that I never see

**Comment by apaulouski** [comment]
Xbox, Bethesda and Battle-net are already amongst the supported platforms. You can check the [full list here](https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md)
While only Xbox is supported officially (it will get the "game pass" update soon), all other mentioned platforms are covered by the community plugins.
