### ISSUE TITLE
Add ability to set game picture

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#4]
Looks like currently there is no way to set game preview picture.
https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/types.py#L94-L105

It would be nice if you add ability to set game preview picture.

**Comment by apaulouski** [comment]
I see you have figured this out (#10), but indeed game info is not supposed to be imported along with game ids/titles.

**Comment by zettend** [comment]
I wanted to add integration with my service. But alas. Add at least the ability to connect to your own JSON service.
