### ISSUE TITLE
Add Community Plugin Repository to README

### ISSUE THREAD

**Issue by RelativeProgramming** [gogcom/galaxy-integrations-python-api#44]
I think a link to
 https://github.com/Mixaill/awesome-gog-galaxy
should be added to the README, so users can find community plugins more easily, since they are directed from the GOG Galaxy Client to this repository.

**Comment by apaulouski** [comment]
Instead of providing links to a third party repositories, we're thinking about adding something more convenient and user-friendly. Please stand by :)

**Comment by apaulouski** [comment]
Any developers who want their plugin to be searchable in the GLX should raise a ticket (GLX -> cogwheel menu -> Report Issue). After that procedure is complete, plugin will be available for all GLX users.
