### ISSUE TITLE
What are the hotkeys, if any?

### ISSUE THREAD

**Issue by Griegorus** [gogcom/galaxy-integrations-python-api#46]
Just a quick question, about hotkeys for typical operations like:
- back (next)
- switch between bookmarks
- look for a game - it would be quite useful on the main GOG page of the store, where there is no "look for a game" - button

**Comment by apaulouski** [comment]
There are no hotkeys in GLX yet.
Please report here only issues related to the python API, and use cogwheel-> Report Issue for general GLX issues.
