### ISSUE TITLE
Games manually added to the Steam are not automatically imported

### ISSUE THREAD

**Issue by Griegorus** [gogcom/galaxy-integrations-python-api#47]
Games manually added to the steam are not automatically imported together with the games bought on steam, so GOG Galaxy 2.0 did not add any of the manually added games from outside of steam, when the steam games were imported.

**Comment by Danyelalejandro** [comment]
I cannot add manually covers to some games. It does not allow it anymore. I have almost 2000 steam games

**Comment by apaulouski** [comment]
This is nothing to do with the plugin API. Please report this issue directly to the plugin developer.
