### ISSUE TITLE
Not all game covers are being imported

### ISSUE THREAD

**Issue by Griegorus** [gogcom/galaxy-integrations-python-api#48]
I cannot add manually covers to some games. It does not allow it anymore. I have almost 2000 steam games

_Originally posted by @Danyelalejandro in https://github.com/gogcom/galaxy-integrations-python-api/issues/47#issuecomment-520239895_

And as above mentioned it is not possible to add covers manually.

**Comment by Griegorus** [comment]
It's actually true for me, for only 2 titles (See screenshot below):
- Talisman: Origins
- Talos Principle VR
![obraz](https://user-images.githubusercontent.com/53795245/62836793-e2d3f480-bc5e-11e9-87be-5a9d84c88bc6.png)

**Comment by apaulouski** [comment]
Please report general GLX issues with cogwheel-> Report Issue, and keep this repo only to python API related issues
