### ISSUE TITLE
Support different format for Game covers

### ISSUE THREAD

**Issue by JigAma** [gogcom/galaxy-integrations-python-api#50]
Most game covers are a tall rectangle shape, but some platforms, like Nintendo DS use a square shaped cover, 

however, GOG Galaxy 2.0 display a rectangular cover for every platforms right now, this is bad because Cover art were designed for the platform format and thus, doesn't look right in another format.

**Comment by apaulouski** [comment]
This is not the right place to report inappropriate game covers. Please use cogwheel menu -> Report Issue from the Galaxy Client.
