### ISSUE TITLE
Feature: custom plugin bookmarks / extend license types

### ISSUE THREAD

**Issue by UncleGoogle** [gogcom/galaxy-integrations-python-api#55]
It would be nice to have ability to manage default bookmarks made by integrations on connection time. Currently there is one bookmark made by default with the platform name and all games returned by "get_owned_games" method

In humblebundle plugin I would create 3 bookmarks for: 
- keys (steam/uplay ect.)
- humble bundle drm-free library
- trove games (monthly subscription games)

The problem is I have no tools to mark duplicated games - its origin or type. I can perform deduplication on plugin side based on priority list defined in user config file, but it is workaround for the actual problem.

Alternatively, Galaxy should add an additional **filter** for "license" type.

BTW I feel there is lack of LicenseType indicating subscription (it is becoming more and more popular along different platforms (like Uplay)).

Then hb integration will return games with different licences:
- SinglePurchase (standard bundles, store purchases)
- Subscription (trove games)
- Free (free games from hb store - they occurs sometimes)
- OtherLicense (3rd party game keys)

**Comment by EustaceCS** [comment]
Hmmmm. Looks like a big feature.
Four types you enlisted are for HumbleBundle.
For Origin it'll be
- Free (? discontinued, however, there's still a lot of games like Dead In Bermuda on gamers' accounts which are not Free to Play but are simply Free)
- Free to Play (Ap... Ape... dat f2p overhyped battle royale :/ I'd kill for possibility to consolidate all f2p ballast in one bookmark - and to hide it from other lists, both automatically)
- Origin Access Basic
- Origin Access Premium
- Purchased
- Trial versions (Dragon Age Inquisition trial, I believe, these are enlisted as separate titles)
- OtherLicense (3rd party - Rainbow Six Siege which could be preordered at Origin some time ago can serve as an example)

**Comment by UncleGoogle** [comment]
@EustaceCS 
It may be big feature for Galaxy, but not for API. There is already way to define Game license:
gogcom/galaxy-integrations-python-api/issues/58

The main thing is what that information serves for in Galaxy. We currenly don't know. Maybe they have some plans. The filtering would be rather side-effect (although very useful).

I don't thing Galaxy is interested in such detailed Licences. It is a platform specific thing. Just for user information if it is kind off demo/trial or full game. My point is to add general license like "subscription" is. And I'm not sure, but looks like "OtherPlatformKey" is also quite popular thing, at least for all kind of store integrations mostly requested to be added to game list, but not only: indiegala, FX store ect.). 

 For Origin example I would just use:
- Free -> `FreeToPlay`
- Free to Play -> `FreeToPlay`
- Origin Access Basic -> `Subscription`
- Origin Access Premium -> `Subscription`
- Purchased -> `SinglePurchase`
- Trial versions -> `Trial`
- OtherLicense -> `OtherLicense` or `Key` depending on situation

**Comment by mbanczerowski** [comment]
Thanks for your proposals, I will pass them on to decision makers.

Currently there are no specific plans to allow bookmarks management by plugins.
As far as subscription licenses are considered, they will be handled in the future with custom names as you suggested (but this is not only a matter of `LicenseType`).

Keys are another story and probably they should be handled in yet another way. "Key" is not logically matter of license, but rather game distribution property. We will talk about it internally. I'm sorry for limited customizability you encountered.

**Comment by SylwesterZarebski** [comment]
Issue on GOG Galaxy 2 tracker: https://mantis2.gog.com/view.php?id=20693

**Comment by mbanczerowski** [comment]
Subscriptions games are already added. Fell free to raport need for special support for `Key`s in Galaxy bugtracker
