### ISSUE TITLE
Gog Galaxy does not delete games which were deleted from integration

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#6]
1. Connect integration whcih returns in  `async def get_owned_games(self):` several games
2. Change the code in such way that integration returns the lower amount of games
3. Reconnect integrations
4. GOG still shows games which are currently not returned by integration.

**Comment by apaulouski** [comment]
Game removal is not possible (?yet). You could instead disconnect a plugin (so all games are removed) and re-connect it again to import only new games.

**Comment by apaulouski** [comment]
This has been fixed in the GLX Client and should be available in the future update.
