### ISSUE TITLE
Plugin data conflicts

### ISSUE THREAD

**Issue by UncleGoogle** [gogcom/galaxy-integrations-python-api#60]
All data the plugin is sending to Galaxy is shared between all user devices. However there is no way for plugins to share data as well, neither directly via some kind of cloud storage (not-local [persistent_cache](https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.api.html#galaxy.api.plugin.Plugin.persistent_cache)), nor through the Galaxy itself.

In case the plugin have ability to modify game list via config, and local settings differs on different devices, there is a race condition for Galaxy backend.

### Example

- Computer A reports 10 games
- Computer B reports 20 games

When get_owned_games call on A and then the same on B, then user on computer A will see sum of A nad B games. When user on A tries run one of those additional games from B, the plugin probably won't recognize the provided game_id and will crash.
Things get even worse when the plugin sends notifications: `remove_game` and `add_game`. Then two plugin are "fighting" by adding and removing games. For example, when user on A change config to show not 10 games but only 2, those lacking games will disappear on computer B, (which may be running idle let say in an another town). In next 30 min. Galaxy on B asks for owned_games and sum of games reported from A and B will be back on both computers.

### Affected:

All plugins that have its own config that modifies data also shared in Galaxy cloud storage. Most probable use-case is list of user owned games. Currently all emulator plugins and humble bundle plugin. And of course, user running plugin instances simultaneously on different devices (which is one of the core concept for Galaxy data syncing I suppose).

### Possible solutions
- The one idea to solve this problem is add a method to store data in cloud storage. This moves effort to plugin developer.

- The alternative is to make owned games "local". But i suppose it's not easy to do and will lead to another problems.

- Yet another solution I can think of is special "locally hidden" state of game. Such game cannot be installed because local instance of the plugin doesn't report it. It will be similar to "hide game" feature, but locally aplicated [and only by plugins] (new API method).

- The last idea depends totally on Galaxy side, it is rather a workaround. Discourage plugins for its own configs by differentiate between game types. And let users filter what they see: free games, subscriptions games, and preferebly plugin owned (named) type of game/license that will be visible on the game view.  (see #55 )

- ?

---
Edit. Pardon for creating issue on integrations API side, not for Galaxy itself, but I wanted to warn other plugin creators.

**Comment by apaulouski** [comment]
First of all, list of _locally installed_ games should be local to a PC and should not conflict with any other plugin instance. If that happens - it's a bug in the GLX client. 
Last time I've checked, backend "accumulated" _owned games_, so if plugins A and B (or the same plugin, with subsequent call to `get_owned_games`) are sending different games, they all will be added to the `owned games` list.
Then, constantly adding and removing _owned games_ looks a bit "synthetic" and is not something a typical human being would do :) People may refund games once in a while, but I'm not sure if that's worth addressing.
The inability of sharing local info is, probably, something we should look at, as this could be useful for "local only"/emulator-ish games. We'll discuss this internally.
