### ISSUE TITLE
Platform list: add Minecraft

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#61]
Requested in https://github.com/Mixaill/awesome-gog-galaxy/issues/17

**Comment by TouwaStar** [comment]
+1, minecraft is one of the biggest selling games of all time and it has its own launcher.

**Comment by Sultzor** [comment]
This should be made available in next update

**Comment by Mixaill** [comment]
Added in https://github.com/gogcom/galaxy-integrations-python-api/commit/8d6ec500f97e74efd709902cad2447dafc1b7397
