### ISSUE TITLE
Add mojang as a platform

### ISSUE THREAD

**Issue by rogersachan** [gogcom/galaxy-integrations-python-api#64]
Mojang plans on distributing minecraft dungeons through the same launcher that minecraft uses, which is why they launched their redesign earlier this year. With a plugin for minecraft already here (https://github.com/TouwaStar/Galaxy_Plugin_Minecraft) it would be ideal to support this platform.

**Comment by TouwaStar** [comment]
imho "mojang" as platform would be better in this case, plugin would be able to handle both of those game regardles of whether they used same launcher or not.

**Comment by rogersachan** [comment]
Closed by release 0.49
