### ISSUE TITLE
Support for Nintendo eShop/myNintendo integration

### ISSUE THREAD

**Issue by smeep0** [gogcom/galaxy-integrations-python-api#65]
I was wondering if it was possible to make GOG Galaxy access your myNintendo account, if only to list down purchases from your library and add them to your game list.

**Comment by apaulouski** [comment]
Sorry, I'm a bit confused: are you asking about the platform definition support (aka enum in `galaxy.api.consts`) or the actual plugin implementation? The later, I'm afraid, is not possible, as that's the purpose of this API - to give the community the ability to implement plugins for all these platforms.

**Comment by smeep0** [comment]
I'd say platform definition support as there isn't even a category for Nintendo Switch on the platform lists.

**Comment by mlindgren** [comment]
It doesn't look to me like Nintendo even has public APIs for accessing account/game information 🙁 There's some unofficial documentation of their REST APIs [here](https://github.com/ZekeSnider/NintendoSwitchRESTAPI), but at least one of the parameters has no known way of being generated outside of the official Switch app.

**Comment by smeep0** [comment]
Is there any way to change platform name from "Other" to specifically "Nintendo Switch"? Seems it doesn't make sense not to list Nintendo's own games under their respective platforms.

**Comment by P1X3L0V4** [comment]
> Is there any way to change platform name from "Other" to specifically "Nintendo Switch"? Seems it doesn't make sense not to list Nintendo's own games under their respective platforms.

You can add new tag called for example "Nintendo Switch" and then add games to it as it was a category.

![](https://i.imgur.com/DzRay0n.png)

**Comment by rbierbasz-gog** [comment]
> I'd say platform definition support as there isn't even a category for Nintendo Switch on the platform lists.

There is `nswitch`: (https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md).

**Comment by smeep0** [comment]
Is there a way to manually add the ```nswitch``` tag under the "Platform" category? In GOG Galaxy it seems preassigned.

@P1X3L0V4 That's what I've been doing but it's not exactly a solution because GOG Galaxy still lists it as "Other" instead of properly recognizing it as a Nintendo Switch game.

**Comment by smeep0** [comment]
Are there still no plans to integrate eShop listed games in GOG?

**Comment by mbanczerowski** [comment]
Closing as unrelated to this project. See https://github.com/gogcom/galaxy-integrations-python-api/issues/new/choose to find proper place to report Galaxy or plugin issues.

You can also propose official integrations in the general feedback [form](https://docs.google.com/forms/d/e/1FAIpQLSfa__KDaxbFseSOFz2ic-XGfIfb7RSbBo4aiXKfgj5Al5EzDw/viewform).
