### ISSUE TITLE
Platform list: add Rockstar Game Launcher

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#68]
* https://socialclub.rockstargames.com/rockstar-games-launcher

**Comment by apaulouski** [comment]
Not sure if this is the same as in #43, or it's a separate one.

**Comment by Mixaill** [comment]
Looks like social club was retired and RGL is the replacement for it.

**Comment by GauthierPLM** [comment]
Was added in a19a6cf11f5deb91445d6c4215680c478df52a23.

**Comment by apaulouski** [comment]
Please not this is only a definition in the API and is not supported by the GLX Client. Should be available with the next big update.
