### ISSUE TITLE
No Support for Bethesda Launcher

### ISSUE THREAD

**Issue by SabreRunner** [gogcom/galaxy-integrations-python-api#70]
Please add support for the Bethesda Launcher ecosystem as I have some important games there which I would very much like to integrate into GOG Galaxy.
Thanks.

**Comment by apaulouski** [comment]
Bethesda is already amongst supported platforms: https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md

**Comment by SabreRunner** [comment]
Oh. I guess I missed that.

**Comment by zule97** [comment]
So how do I add Bethesda Launcher on GOG Galaxy? Can anyone help please?

**Comment by SabreRunner** [comment]
I still haven't figured it out.

**Comment by Mixaill** [comment]
@zule97, @SabreRunner : download windows.zip from https://github.com/FriendsOfGalaxy/galaxy-integration-bethesda/releases and unpack it to %localappdata%\GOG.com\Galaxy\plugins\installed
