### ISSUE TITLE
Platform List: add Itch.io

### ISSUE THREAD

**Issue by SpikeDaPenguin** [gogcom/galaxy-integrations-python-api#75]
Itch.io is a great place for indie games both free and bought.  Please add the ability to sync all Itch.io purchases to GOG 2.0

**Comment by EustaceCS** [comment]
I'm probably missing something hidden in plain sight, but for me itch.io is already there!
![Снимок](https://user-images.githubusercontent.com/29461793/66714995-94f67c80-edc6-11e9-9d18-edf2fe835ea8.PNG)
Please refer to https://github.com/Mixaill/awesome-gog-galaxy for most current list of integrations - it's in there.

**Comment by apaulouski** [comment]
@EustaceCS described this well.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/70753677-3b122480-1d2d-11ea-8aab-15341c216474.png)
![image](https://user-images.githubusercontent.com/13716824/70753690-3f3e4200-1d2d-11ea-97a2-b06d20706fcf.png)

I don't have itch anywhere

**Comment by Darxide23** [comment]
I'm having this same issue. My integrations settings look just like @ChildishGiant

**Comment by mbanczerowski** [comment]
Hi, not all community integrations are supported in build-in serach. More comprehensive list of those can be find here: https://github.com/Mixaill/awesome-gog-galaxy
Note that they have to be added manually.
