### ISSUE TITLE
Open Source Re-implementations

### ISSUE THREAD

**Issue by ben132** [gogcom/galaxy-integrations-python-api#78]
I don't know whether this is already possible.  But Launching a Game through the Launcher that uses the same open source engine.  For example opening Red Alert or Command and Conquer with OpenRA, but not with multiple instances of the OpenRA engine.

**Comment by apaulouski** [comment]
When starting a game, plugin will just receive game id to launch. It's up to plugin/plugin developer on how the game shall be executed, and has nothing to do with the plugins API.
