### ISSUE TITLE
Add Twitch Games support

### ISSUE THREAD

**Issue by Noelierx** [gogcom/galaxy-integrations-python-api#82]
With Twitch Prime, you can obtain some games. To play with them, you need to download the Twitch App and install games. 
Adding a support for this twitch app, especially for game would be awesome.

**Comment by apaulouski** [comment]
Twitch platform definition is already on the list of supported platform, see https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py

**Comment by SeidChr** [comment]
I cannot add twitch in GOG Galaxy 2
