### ISSUE TITLE
Platform list: add support for Battle.net

### ISSUE THREAD

**Issue by Majinthew** [gogcom/galaxy-integrations-python-api#83]
Is it possible to add platform integration with Blizzard's battle.net launcher? Most of my playtime is spent on games from Blizzard: Warcraft, Diablo, and Hearthstone. They are some pretty major titles that I feel should be available if GOG Galaxy is to be my main gaming hub.

**Comment by apaulouski** [comment]
Battle.net is already on the [list of supported platforms](https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/consts.py).

It's up to the community to implement actual plugin. Maybe they already implemented one.
