### ISSUE TITLE
User Presence does not work for community integration

### ISSUE THREAD

**Issue by Mixaill** [gogcom/galaxy-integrations-python-api#89]
Trying to add support for user presence for Wargaming integration ( https://github.com/Mixaill/galaxy-integration-wargaming ), but for some reason it does not works.

1) `get_friends()` output
```
2019-12-08 01:50:54,047 - root - INFO - get_friends: [
...
UserInfo(
    user_id='6825084', 
    user_name='RU_P0LIR0ID', 
    avatar_url= None, 
    profile_url='https://worldoftanks.ru/ru/community/accounts/6825084'),
...
]
```

2) `get_user_presence()` output

```
2019-12-08 01:51:23,033 - galaxy.api.jsonrpc - INFO - Sending notification: method=user_presence_import_success, params={
    'user_id': '6825084', 
    'presence': UserPresence(
        presence_state=<PresenceState.Online: 'online'>, 
        game_id='WOT.RU.PRODUCTION', 
        game_title='World of Tanks (RU)', 
        in_game_status=None, 
        full_status=None)
   }
```

3) There is record in `GalaxyClient.log`

```
2019-12-08 01:58:53.864 [Information][ (0)] [TID 17076][galaxy_client]: Presence (state: online, game id: wargaming_WOT.RU.PRODUCTION, game title: World of Tanks (RU), in_game_status: <<NULL>>, full_status: <<NULL>>) imported for user u/wargaming_6825084.
2019-12-08 01:58:53.864 [Information][ (0)] [TID 17076][galaxy_client]: Successfully imported presence information for user u/wargaming_8332677
```

But I still does not see Wargaming subgroup in friends panel
![image](https://user-images.githubusercontent.com/704382/70381615-780d9e00-195e-11ea-9587-0bea17150db3.png)

**Comment by rbierbasz-gog** [comment]
Which version of the API do you use?

**Comment by Mixaill** [comment]
0.61

**Comment by rbierbasz-gog** [comment]
OK - due to big load on the backend service (open beta) this future was turn on only for several platforms. It should be turn on for all next week - I'll let you know when it's ready.

**Comment by Sultzor** [comment]
It should be switched on for Wargaming and Rockstar plugins as well currently

**Comment by tylerbrawl** [comment]
@rbierbasz-gog - Thank you so much for the confirmation. I spent hours thinking that the problem was on my side, but I am glad to see that the feature was just temporarily disabled for the Rockstar plugin.

**Comment by Mixaill** [comment]
Works for Wargaming

![image](https://user-images.githubusercontent.com/704382/70656401-13f31e80-1c6b-11ea-8825-9df7ceead4b5.png)
