### ISSUE TITLE
Add "Battle.net" Feature

### ISSUE THREAD

**Issue by MaartenBl** [gogcom/galaxy-integrations-python-api#91]
Curious if it's possible to add battle.net integration.

**Comment by apawlowskij** [comment]
duplicate

**Comment by Mixaill** [comment]
@MaartenBl https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet/releases

**Comment by MaartenBl** [comment]
Thanks for the link, couldn't find it in the client.
![image](https://user-images.githubusercontent.com/19569456/70453508-2aea1300-1aa9-11ea-8628-69f892ddeacd.png)

**Comment by KleyArk** [comment]
> 
> 
> Thanks for the link, couldn't find it in the client.
> ![image](https://user-images.githubusercontent.com/19569456/70453508-2aea1300-1aa9-11ea-8628-69f892ddeacd.png)

Me too. I tried to search the keyword "Blizzard", "Battle.net", "net" and "battlenet", but there's nothing.
How can we implement it @Mixaill ?

**Comment by KleyArk** [comment]
> 
> 
> Thanks for the link, couldn't find it in the client.
> ![image](https://user-images.githubusercontent.com/19569456/70453508-2aea1300-1aa9-11ea-8628-69f892ddeacd.png)

Follow these instructions:
https://i.imgur.com/XQkKp0R.png

Then open Gog Galaxy again and you should have available Battle.net as an integration option ;)
