### ISSUE TITLE
Request: Please add DOS or DOSBOX as a platform

### ISSUE THREAD

**Issue by RoorMakurosu** [gogcom/galaxy-integrations-python-api#94]
I've been working on a integration to DOS games (under Dosbox and others), but I've been forced to set the platform as "Atari Jaguar" just to make it run... 

I can't release it like that :'(

**Comment by d0rkm4n** [comment]
> I've been working on a integration to DOS games (under Dosbox and others), but I've been forced to set the platform as "Atari Jaguar" just to make it run...
> 
> I can't release it like that :'(

Much appreciated! Looking forward for that as I've manually added plenty of DOS games myself.
A real PITA...

![retrogamelist](https://user-images.githubusercontent.com/60705907/73858851-5be08d00-4839-11ea-9b08-0b3e8983b252.png)

**Comment by RoorMakurosu** [comment]
Yeahh... me too.
I even created a modified dosbox that reads games from "packaged ROMS" which are actual compressed DOS games.

I made multiple integrations myself (to be honest, 70% of them are all the same) to integrate emulators and other stuff. Haven't published anything so far...

![GG](https://user-images.githubusercontent.com/8114142/73860168-e7e2bc80-4819-11ea-89dc-971b04a2fc91.jpg)

**Comment by d0rkm4n** [comment]
Sounds good, love your idea!
So your modified Dosbox is able to autoadd games that are compressed? What about simple folders?

**Comment by RoorMakurosu** [comment]
No. You for it wrong.

I heavily modified DosBox so it can run games directly from compressed files (7Z, ZIP & RAR).>
It even autodetects ISO images or CDROM folders inside them, and mount them directly.

Separately, I made my own GOG Galaxy plugin that detects these files, and add them to GOGG, and allows you to launch them (using the same dosbox, which I embedded into the plugin) as well as track the play time.

That's it.

**Comment by d0rkm4n** [comment]
Aaah, thanks for pointing that out! :-) 
I've modified mine aswell, somewhat like the gogwrapper in combination with scummvm, it works folder based and I use DFEND for keeping track on all the entries and let create .bat files for every game to import them in GOG Galaxy. 

Atm I do the GOG import of the .bat files manually - until stumbled over your plugin and wanted to give it a try. At first a big THANK YOU for your effort! Good to see that I'm not the only one missing a dosbox integration in GOG Galaxy.

Couldn't get the plugin to work yet though. May I ask where I've to put the plugin folder and what you've to do to run it? 

Thanks in advance and greets from Germany!

**Comment by RoorMakurosu** [comment]
I'll push an update to it soon, and let you know.
I have a pretty busy week.
You can PM me on twitter (torumcom)

Regards.

**Comment by mbanczerowski** [comment]
Aggregated in issue mentioned above
