### ISSUE TITLE
Request: VR Platform and Store Additions

### ISSUE THREAD

**Issue by jwmarrott** [gogcom/galaxy-integrations-python-api#96]
Store:
Oculus
Sidequest
Viveport
SteamVR ??

Platforms:
Vive
PSVR
Oculus Go
Oculus Rift/Rift S
Oculus Quest
Valve Index

**Comment by Sokonomi** [comment]
This has my vote as well. I wish I could plop my oculus game list in.

**Comment by tombuben** [comment]
SteamVR shouldn't really be considered a separate store or a platform really, it's just an API. Honestly it's more of a platform than a store. The thing missing right now in the integrations ID list are the three VR exclusive storefronts (Oculus, Viveport, Sidequest).

Better support for VR in general would be welcome (Eg, Steam labels with which headsets the game are compatible), but those changes would be a lot harder than adding the store IDs right now.

**Comment by jwmarrott** [comment]
Agreed on Steam VR. As I have gotten more into VR it doesn’t make sense. However it would be nice to have a VR watermark on VR games in the steam store

**Comment by pulse4J** [comment]
I'd love full support for SteamVR as well.  It would be great to get Oculus, and also have an option on launch to use Revive for those of us not using an Oculus headset.  If you need a tester, please contact me.  Thanks.

**Comment by Megalomac** [comment]
Oculus support would be fantastic! To me, SteamVR works because Steam works well.  I just tag the VR games with a VR tag and added as a bookmark to the left nav.

**Comment by mbanczerowski** [comment]
Aggregated in mentioned task.
