### ISSUE TITLE
Support for: GameJolt, EnMasse, Arc, Indigala

### ISSUE THREAD

**Issue by ArtexJay** [gogcom/galaxy-integrations-python-api#97]
Please add support for connecting GOG 2.0 client with these clients if that's at all possible
1. En Masse game Client 
2. Gamejolt (would be amazing if you could support its notifications as well as friend list/chat)
3. Arc Game Client with your game library and friend list/chat
4. Indigala account support to import games in the your library

**Comment by Lambik** [comment]
+1 for indiegala

**Comment by mbanczerowski** [comment]
Aggregated in mentioned task.
