### ISSUE TITLE
Request: please add GamersGate as an integration

### ISSUE THREAD

**Issue by SeaMarc** [gogcom/galaxy-integrations-python-api#98]
I own a number of games on GamersGate and would love to add them to my library in this awesome GOG tool

**Comment by UncleGoogle** [comment]
This is wrong place to ask about it. GamersGate is already on the API list:
https://github.com/gogcom/galaxy-integrations-python-api/blob/master/PLATFORM_IDs.md
Write an issue on this community repository: https://github.com/Mixaill/awesome-gog-galaxy
